# Generated by Django 4.1.1 on 2022-10-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efarm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
