# Generated by Django 4.1.1 on 2022-10-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efarm', '0003_blog_content_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
