# Generated by Django 4.1.1 on 2022-10-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('efarm', '0004_blog_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centremanager',
            name='county',
        ),
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=254)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efarm.county')),
            ],
        ),
        migrations.AddField(
            model_name='centremanager',
            name='centre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='efarm.centre'),
        ),
    ]
