# Generated by Django 4.1.1 on 2022-10-19 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('efarm', '0005_remove_centremanager_county_centre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centremanager',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efarm.centre'),
        ),
    ]
