# Generated by Django 4.1.1 on 2022-10-19 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('efarm', '0006_alter_centremanager_centre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='county',
        ),
        migrations.AddField(
            model_name='farmer',
            name='centre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='efarm.centre'),
        ),
    ]
