# Generated by Django 4.1.1 on 2022-10-19 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('efarm', '0007_remove_farmer_county_farmer_centre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('paypalTransactionId', models.CharField(max_length=100, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='efarm.buyer')),
            ],
        ),
        migrations.AlterField(
            model_name='farmer',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efarm.centre'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='VAT',
            field=models.DecimalField(decimal_places=2, default=16, max_digits=10),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='efarm.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='efarm.produce')),
            ],
        ),
    ]
