# Generated by Django 4.1.1 on 2022-10-19 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('efarm', '0008_order_alter_farmer_centre_alter_invoice_vat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='efarm.buyer'),
        ),
    ]
