# Generated by Django 4.1.1 on 2022-10-20 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efarm', '0011_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
